{
  "patcher": {
    "fileversion": 1,
    "appversion": {
      "major": 9,
      "minor": 1,
      "revision": 4,
      "architecture": "x64",
      "modernui": 1
    },
    "classnamespace": "box",
    "rect": [60.0, 60.0, 1180.0, 820.0],
    "openinpresentation": 1,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [15.0, 15.0],
    "bglocked": 0,
    "boxes": [
      {"box": {"id": "obj-title", "maxclass": "comment", "text": "RESPONSIBLE AI SENSIFICATION — OSC RECEIVER", "fontsize": 16.0, "fontface": 1, "patching_rect": [20.0, 15.0, 500.0, 24.0], "presentation": 1, "presentation_rect": [15.0, 10.0, 500.0, 24.0]}},
      {"box": {"id": "obj-subtitle", "maxclass": "comment", "text": "UDP is connectionless: this device reports listening or receiving, never connected.", "textcolor": [0.55, 0.58, 0.65, 1.0], "patching_rect": [20.0, 40.0, 560.0, 20.0], "presentation": 1, "presentation_rect": [15.0, 34.0, 560.0, 20.0]}},

      {"box": {"id": "obj-port-label", "maxclass": "comment", "text": "UDP PORT", "patching_rect": [610.0, 15.0, 70.0, 20.0], "presentation": 1, "presentation_rect": [590.0, 12.0, 68.0, 20.0]}},
      {"box": {"id": "obj-port-ui", "maxclass": "number", "minimum": 1, "maximum": 65535, "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "patching_rect": [680.0, 15.0, 65.0, 22.0], "presentation": 1, "presentation_rect": [660.0, 10.0, 68.0, 22.0]}},
      {"box": {"id": "obj-gain-label", "maxclass": "comment", "text": "PREVIEW GAIN", "patching_rect": [610.0, 43.0, 95.0, 20.0], "presentation": 1, "presentation_rect": [590.0, 39.0, 92.0, 20.0]}},
      {"box": {"id": "obj-gain-ui", "maxclass": "flonum", "minimum": 0.0, "maximum": 0.8, "format": 6, "numinlets": 1, "numoutlets": 2, "outlettype": ["float", "bang"], "patching_rect": [710.0, 43.0, 65.0, 22.0], "presentation": 1, "presentation_rect": [686.0, 37.0, 65.0, 22.0]}},
      {"box": {"id": "obj-mute-label", "maxclass": "comment", "text": "MUTE", "patching_rect": [790.0, 15.0, 45.0, 20.0], "presentation": 1, "presentation_rect": [770.0, 12.0, 42.0, 20.0]}},
      {"box": {"id": "obj-mute-ui", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [840.0, 15.0, 22.0, 22.0], "presentation": 1, "presentation_rect": [816.0, 10.0, 22.0, 22.0]}},
      {"box": {"id": "obj-reset-label", "maxclass": "comment", "text": "RESET", "patching_rect": [790.0, 43.0, 45.0, 20.0], "presentation": 1, "presentation_rect": [770.0, 39.0, 44.0, 20.0]}},
      {"box": {"id": "obj-reset-ui", "maxclass": "button", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [840.0, 43.0, 22.0, 22.0], "presentation": 1, "presentation_rect": [816.0, 37.0, 22.0, 22.0]}},
      {"box": {"id": "obj-preview-label", "maxclass": "comment", "text": "STANDALONE AUDIO", "patching_rect": [885.0, 15.0, 125.0, 20.0], "presentation": 1, "presentation_rect": [855.0, 12.0, 125.0, 20.0]}},
      {"box": {"id": "obj-ezdac", "maxclass": "ezdac~", "numinlets": 2, "numoutlets": 0, "patching_rect": [1015.0, 15.0, 45.0, 45.0], "presentation": 1, "presentation_rect": [985.0, 8.0, 45.0, 45.0]}},
      {"box": {"id": "obj-panel", "maxclass": "jsui", "filename": "rai_receiver_panel.js", "jsarguments": [], "border": 0, "numinlets": 1, "numoutlets": 0, "parameter_enable": 0, "patching_rect": [20.0, 90.0, 1040.0, 370.0], "presentation": 1, "presentation_rect": [15.0, 70.0, 1030.0, 370.0]}},
      {"box": {"id": "obj-meter", "maxclass": "meter~", "numinlets": 1, "numoutlets": 1, "outlettype": ["float"], "patching_rect": [1075.0, 90.0, 18.0, 370.0], "presentation": 1, "presentation_rect": [1052.0, 70.0, 18.0, 370.0]}},

      {"box": {"id": "obj-udp", "maxclass": "newobj", "text": "udpreceive 9000", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [20.0, 510.0, 105.0, 22.0]}},
      {"box": {"id": "obj-js", "maxclass": "newobj", "text": "js rai_osc_receiver.js", "numinlets": 2, "numoutlets": 3, "outlettype": ["", "", ""], "patching_rect": [20.0, 555.0, 145.0, 22.0]}},
      {"box": {"id": "obj-diag-filter", "maxclass": "newobj", "text": "route port master_gain mute", "numinlets": 1, "numoutlets": 4, "outlettype": ["", "", "", ""], "patching_rect": [190.0, 600.0, 175.0, 22.0]}},
      {"box": {"id": "obj-namespace", "maxclass": "newobj", "text": "rai_ossia_namespace", "numinlets": 1, "numoutlets": 3, "outlettype": ["", "", ""], "patching_rect": [390.0, 600.0, 135.0, 22.0]}},
      {"box": {"id": "obj-poly", "maxclass": "newobj", "text": "poly~ rai_osc_voice 16 @steal 1", "numinlets": 1, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [20.0, 645.0, 190.0, 22.0]}},

      {"box": {"id": "obj-load-port", "maxclass": "newobj", "text": "loadmess 9000", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [610.0, 510.0, 88.0, 22.0]}},
      {"box": {"id": "obj-load-gain", "maxclass": "newobj", "text": "loadmess 0.35", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [710.0, 510.0, 92.0, 22.0]}},
      {"box": {"id": "obj-load-mute", "maxclass": "newobj", "text": "loadmess 0", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [815.0, 510.0, 75.0, 22.0]}},
      {"box": {"id": "obj-prepend-port-ui", "maxclass": "newobj", "text": "prepend port", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [610.0, 555.0, 85.0, 22.0]}},
      {"box": {"id": "obj-prepend-gain-ui", "maxclass": "newobj", "text": "prepend master_gain", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [710.0, 555.0, 125.0, 22.0]}},
      {"box": {"id": "obj-prepend-mute-ui", "maxclass": "newobj", "text": "prepend mute", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [845.0, 555.0, 88.0, 22.0]}},
      {"box": {"id": "obj-reset-message", "maxclass": "message", "text": "reset", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [950.0, 555.0, 42.0, 22.0]}},

      {"box": {"id": "obj-port-trigger", "maxclass": "newobj", "text": "t i i", "numinlets": 1, "numoutlets": 2, "outlettype": ["int", "int"], "patching_rect": [390.0, 645.0, 42.0, 22.0]}},
      {"box": {"id": "obj-gain-trigger", "maxclass": "newobj", "text": "t f f f", "numinlets": 1, "numoutlets": 3, "outlettype": ["float", "float", "float"], "patching_rect": [470.0, 645.0, 55.0, 22.0]}},
      {"box": {"id": "obj-mute-trigger", "maxclass": "newobj", "text": "t i i i", "numinlets": 1, "numoutlets": 3, "outlettype": ["int", "int", "int"], "patching_rect": [560.0, 645.0, 55.0, 22.0]}},
      {"box": {"id": "obj-set-port", "maxclass": "newobj", "text": "prepend set", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [390.0, 685.0, 78.0, 22.0]}},
      {"box": {"id": "obj-set-gain", "maxclass": "newobj", "text": "prepend set", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [480.0, 685.0, 78.0, 22.0]}},
      {"box": {"id": "obj-set-mute", "maxclass": "newobj", "text": "prepend set", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [570.0, 685.0, 78.0, 22.0]}},
      {"box": {"id": "obj-port-to-js", "maxclass": "newobj", "text": "prepend port", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [390.0, 725.0, 85.0, 22.0]}},
      {"box": {"id": "obj-gain-to-js", "maxclass": "newobj", "text": "prepend master_gain", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [480.0, 725.0, 125.0, 22.0]}},
      {"box": {"id": "obj-mute-to-js", "maxclass": "newobj", "text": "prepend mute", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [615.0, 725.0, 88.0, 22.0]}},

      {"box": {"id": "obj-master-expr", "maxclass": "newobj", "text": "expr $f1 * (1. - $f2)", "numinlets": 2, "numoutlets": 1, "outlettype": ["float"], "patching_rect": [730.0, 645.0, 140.0, 22.0]}},
      {"box": {"id": "obj-master-pack", "maxclass": "newobj", "text": "pack 0. 20", "numinlets": 2, "numoutlets": 1, "outlettype": ["list"], "patching_rect": [730.0, 685.0, 72.0, 22.0]}},
      {"box": {"id": "obj-master-line", "maxclass": "newobj", "text": "line~ 0.", "numinlets": 2, "numoutlets": 2, "outlettype": ["signal", "bang"], "patching_rect": [730.0, 725.0, 55.0, 22.0]}},
      {"box": {"id": "obj-preview-gain", "maxclass": "newobj", "text": "*~", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [225.0, 645.0, 32.0, 22.0]}},
      {"box": {"id": "obj-preview-tanh", "maxclass": "newobj", "text": "tanh~", "numinlets": 1, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [275.0, 645.0, 42.0, 22.0]}},

      {"box": {"id": "obj-plugin", "maxclass": "newobj", "text": "plugin~", "numinlets": 0, "numoutlets": 2, "outlettype": ["signal", "signal"], "patching_rect": [20.0, 700.0, 52.0, 22.0]}},
      {"box": {"id": "obj-mix-left", "maxclass": "newobj", "text": "+~", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [90.0, 700.0, 32.0, 22.0]}},
      {"box": {"id": "obj-mix-right", "maxclass": "newobj", "text": "+~", "numinlets": 2, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [140.0, 700.0, 32.0, 22.0]}},
      {"box": {"id": "obj-clip-left", "maxclass": "newobj", "text": "clip~ -0.98 0.98", "numinlets": 3, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [90.0, 745.0, 100.0, 22.0]}},
      {"box": {"id": "obj-clip-right", "maxclass": "newobj", "text": "clip~ -0.98 0.98", "numinlets": 3, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [205.0, 745.0, 100.0, 22.0]}},
      {"box": {"id": "obj-plugout", "maxclass": "newobj", "text": "plugout~", "numinlets": 2, "numoutlets": 0, "patching_rect": [320.0, 745.0, 55.0, 22.0]}},

      {"box": {"id": "obj-audio-comment", "maxclass": "comment", "text": "The Max Audio Effect passes input through and adds only the bounded preview synth.", "patching_rect": [20.0, 785.0, 500.0, 20.0]}}
    ],
    "lines": [
      {"patchline": {"source": ["obj-udp", 0], "destination": ["obj-js", 0]}},
      {"patchline": {"source": ["obj-js", 0], "destination": ["obj-poly", 0]}},
      {"patchline": {"source": ["obj-js", 1], "destination": ["obj-panel", 0]}},
      {"patchline": {"source": ["obj-js", 1], "destination": ["obj-diag-filter", 0]}},
      {"patchline": {"source": ["obj-diag-filter", 3], "destination": ["obj-namespace", 0]}},
      {"patchline": {"source": ["obj-js", 2], "destination": ["obj-udp", 0]}},

      {"patchline": {"source": ["obj-load-port", 0], "destination": ["obj-port-ui", 0]}},
      {"patchline": {"source": ["obj-load-gain", 0], "destination": ["obj-gain-ui", 0]}},
      {"patchline": {"source": ["obj-load-mute", 0], "destination": ["obj-mute-ui", 0]}},
      {"patchline": {"source": ["obj-port-ui", 0], "destination": ["obj-prepend-port-ui", 0]}},
      {"patchline": {"source": ["obj-gain-ui", 0], "destination": ["obj-prepend-gain-ui", 0]}},
      {"patchline": {"source": ["obj-mute-ui", 0], "destination": ["obj-prepend-mute-ui", 0]}},
      {"patchline": {"source": ["obj-prepend-port-ui", 0], "destination": ["obj-namespace", 0]}},
      {"patchline": {"source": ["obj-prepend-gain-ui", 0], "destination": ["obj-namespace", 0]}},
      {"patchline": {"source": ["obj-prepend-mute-ui", 0], "destination": ["obj-namespace", 0]}},
      {"patchline": {"source": ["obj-reset-ui", 0], "destination": ["obj-reset-message", 0]}},
      {"patchline": {"source": ["obj-reset-message", 0], "destination": ["obj-js", 1]}},

      {"patchline": {"source": ["obj-namespace", 0], "destination": ["obj-port-trigger", 0]}},
      {"patchline": {"source": ["obj-namespace", 1], "destination": ["obj-gain-trigger", 0]}},
      {"patchline": {"source": ["obj-namespace", 2], "destination": ["obj-mute-trigger", 0]}},
      {"patchline": {"source": ["obj-port-trigger", 0], "destination": ["obj-port-to-js", 0]}},
      {"patchline": {"source": ["obj-port-trigger", 1], "destination": ["obj-set-port", 0]}},
      {"patchline": {"source": ["obj-set-port", 0], "destination": ["obj-port-ui", 0]}},
      {"patchline": {"source": ["obj-port-to-js", 0], "destination": ["obj-js", 1]}},
      {"patchline": {"source": ["obj-gain-trigger", 0], "destination": ["obj-gain-to-js", 0]}},
      {"patchline": {"source": ["obj-gain-trigger", 1], "destination": ["obj-master-expr", 0]}},
      {"patchline": {"source": ["obj-gain-trigger", 2], "destination": ["obj-set-gain", 0]}},
      {"patchline": {"source": ["obj-set-gain", 0], "destination": ["obj-gain-ui", 0]}},
      {"patchline": {"source": ["obj-gain-to-js", 0], "destination": ["obj-js", 1]}},
      {"patchline": {"source": ["obj-mute-trigger", 0], "destination": ["obj-mute-to-js", 0]}},
      {"patchline": {"source": ["obj-mute-trigger", 1], "destination": ["obj-master-expr", 1]}},
      {"patchline": {"source": ["obj-mute-trigger", 2], "destination": ["obj-set-mute", 0]}},
      {"patchline": {"source": ["obj-set-mute", 0], "destination": ["obj-mute-ui", 0]}},
      {"patchline": {"source": ["obj-mute-to-js", 0], "destination": ["obj-js", 1]}},

      {"patchline": {"source": ["obj-master-expr", 0], "destination": ["obj-master-pack", 0]}},
      {"patchline": {"source": ["obj-master-pack", 0], "destination": ["obj-master-line", 0]}},
      {"patchline": {"source": ["obj-poly", 0], "destination": ["obj-preview-gain", 0]}},
      {"patchline": {"source": ["obj-master-line", 0], "destination": ["obj-preview-gain", 1]}},
      {"patchline": {"source": ["obj-preview-gain", 0], "destination": ["obj-preview-tanh", 0]}},

      {"patchline": {"source": ["obj-plugin", 0], "destination": ["obj-mix-left", 0]}},
      {"patchline": {"source": ["obj-plugin", 1], "destination": ["obj-mix-right", 0]}},
      {"patchline": {"source": ["obj-preview-tanh", 0], "destination": ["obj-mix-left", 1]}},
      {"patchline": {"source": ["obj-preview-tanh", 0], "destination": ["obj-mix-right", 1]}},
      {"patchline": {"source": ["obj-mix-left", 0], "destination": ["obj-clip-left", 0]}},
      {"patchline": {"source": ["obj-mix-right", 0], "destination": ["obj-clip-right", 0]}},
      {"patchline": {"source": ["obj-clip-left", 0], "destination": ["obj-plugout", 0]}},
      {"patchline": {"source": ["obj-clip-right", 0], "destination": ["obj-plugout", 1]}},
      {"patchline": {"source": ["obj-clip-left", 0], "destination": ["obj-ezdac", 0]}},
      {"patchline": {"source": ["obj-clip-right", 0], "destination": ["obj-ezdac", 1]}},
      {"patchline": {"source": ["obj-clip-left", 0], "destination": ["obj-meter", 0]}}
    ],
    "dependency_cache": [
      {"name": "rai_osc_receiver.js", "bootpath": ".", "type": "TEXT", "implicit": 1},
      {"name": "rai_receiver_panel.js", "bootpath": ".", "type": "TEXT", "implicit": 1},
      {"name": "rai_ossia_namespace.maxpat", "bootpath": ".", "type": "JSON", "implicit": 1},
      {"name": "rai_osc_voice.maxpat", "bootpath": ".", "type": "JSON", "implicit": 1}
    ]
  }
}
