{
  "patcher": {
    "fileversion": 1,
    "appversion": {
      "major": 9,
      "minor": 1,
      "revision": 4,
      "architecture": "x64",
      "modernui": 1
    },
    "classnamespace": "box",
    "rect": [80.0, 80.0, 1500.0, 920.0],
    "openinpresentation": 0,
    "default_fontsize": 11.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "gridonopen": 1,
    "gridsize": [15.0, 15.0],
    "boxes": [
      {"box": {"id": "obj-in", "maxclass": "newobj", "text": "in 1", "numinlets": 0, "numoutlets": 1, "outlettype": [""], "patching_rect": [20.0, 20.0, 30.0, 22.0]}},
      {"box": {"id": "obj-route", "maxclass": "newobj", "text": "route port master_gain mute state run_state run_id sequence token_text note_count tonality bpm mode loop tonality_enabled prompt_influence pitch_bias last_frequency last_activation last_feature last_cluster last_instrument last_error unknown_count release_count last_release_reason last_frame_json", "numinlets": 1, "numoutlets": 27, "outlettype": ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], "patching_rect": [20.0, 60.0, 1400.0, 22.0]}},

      {"box": {"id": "obj-device", "maxclass": "newobj", "text": "ossia.device rai_receiver", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 845.0, 150.0, 22.0]}},
      {"box": {"id": "obj-expose", "maxclass": "newobj", "text": "loadmess expose oscquery 9011 5679", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [20.0, 805.0, 215.0, 22.0]}},

      {"box": {"id": "obj-port", "maxclass": "newobj", "text": "ossia.parameter config/port @type int @default 9000 @range 1 65535 @clip both @access both", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 115.0, 550.0, 22.0]}},
      {"box": {"id": "obj-gain", "maxclass": "newobj", "text": "ossia.parameter config/master_gain @type float @default 0.35 @range 0. 0.8 @clip both @access both", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 150.0, 590.0, 22.0]}},
      {"box": {"id": "obj-mute", "maxclass": "newobj", "text": "ossia.parameter config/mute @type bool @default 0 @access both", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 185.0, 410.0, 22.0]}},
      {"box": {"id": "obj-out-port", "maxclass": "newobj", "text": "out 1", "numinlets": 1, "numoutlets": 0, "patching_rect": [650.0, 115.0, 35.0, 22.0]}},
      {"box": {"id": "obj-out-gain", "maxclass": "newobj", "text": "out 2", "numinlets": 1, "numoutlets": 0, "patching_rect": [650.0, 150.0, 35.0, 22.0]}},
      {"box": {"id": "obj-out-mute", "maxclass": "newobj", "text": "out 3", "numinlets": 1, "numoutlets": 0, "patching_rect": [650.0, 185.0, 35.0, 22.0]}},

      {"box": {"id": "obj-state", "maxclass": "newobj", "text": "ossia.parameter status/state @type string @default listening @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 255.0, 440.0, 22.0]}},
      {"box": {"id": "obj-run-state", "maxclass": "newobj", "text": "ossia.parameter status/run_state @type string @default idle @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [490.0, 255.0, 450.0, 22.0]}},
      {"box": {"id": "obj-run-id", "maxclass": "newobj", "text": "ossia.parameter status/run_id @type string @default none @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [970.0, 255.0, 430.0, 22.0]}},
      {"box": {"id": "obj-sequence", "maxclass": "newobj", "text": "ossia.parameter status/sequence @type int @default -1 @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 295.0, 410.0, 22.0]}},
      {"box": {"id": "obj-token", "maxclass": "newobj", "text": "ossia.parameter status/token_text @type string @default none @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [490.0, 295.0, 455.0, 22.0]}},
      {"box": {"id": "obj-note-count", "maxclass": "newobj", "text": "ossia.parameter status/note_count @type int @default 0 @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [970.0, 295.0, 415.0, 22.0]}},
      {"box": {"id": "obj-tonality", "maxclass": "newobj", "text": "ossia.parameter status/tonality @type string @default none @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 335.0, 440.0, 22.0]}},
      {"box": {"id": "obj-bpm", "maxclass": "newobj", "text": "ossia.parameter status/bpm @type int @default 120 @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [490.0, 335.0, 390.0, 22.0]}},
      {"box": {"id": "obj-mode", "maxclass": "newobj", "text": "ossia.parameter status/mode @type string @default timed @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [970.0, 335.0, 430.0, 22.0]}},
      {"box": {"id": "obj-loop", "maxclass": "newobj", "text": "ossia.parameter status/loop @type bool @default 0 @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 375.0, 390.0, 22.0]}},
      {"box": {"id": "obj-tonality-enabled", "maxclass": "newobj", "text": "ossia.parameter status/tonality_enabled @type bool @default 0 @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [490.0, 375.0, 475.0, 22.0]}},
      {"box": {"id": "obj-prompt", "maxclass": "newobj", "text": "ossia.parameter status/prompt_influence @type float @default 0. @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [970.0, 375.0, 455.0, 22.0]}},
      {"box": {"id": "obj-pitch", "maxclass": "newobj", "text": "ossia.parameter status/pitch_bias @type float @default 0. @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 415.0, 430.0, 22.0]}},
      {"box": {"id": "obj-frequency", "maxclass": "newobj", "text": "ossia.parameter status/last_frequency @type float @default 0. @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [490.0, 415.0, 460.0, 22.0]}},
      {"box": {"id": "obj-activation", "maxclass": "newobj", "text": "ossia.parameter status/last_activation @type float @default 0. @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [970.0, 415.0, 465.0, 22.0]}},
      {"box": {"id": "obj-feature", "maxclass": "newobj", "text": "ossia.parameter status/last_feature @type int @default -1 @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 455.0, 435.0, 22.0]}},
      {"box": {"id": "obj-cluster", "maxclass": "newobj", "text": "ossia.parameter status/last_cluster @type int @default -1 @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [490.0, 455.0, 440.0, 22.0]}},
      {"box": {"id": "obj-instrument", "maxclass": "newobj", "text": "ossia.parameter status/last_instrument @type string @default none @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [970.0, 455.0, 475.0, 22.0]}},
      {"box": {"id": "obj-error", "maxclass": "newobj", "text": "ossia.parameter status/last_error @type string @default none @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 495.0, 445.0, 22.0]}},
      {"box": {"id": "obj-unknown", "maxclass": "newobj", "text": "ossia.parameter status/unknown_count @type int @default 0 @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [490.0, 495.0, 440.0, 22.0]}},
      {"box": {"id": "obj-release-count", "maxclass": "newobj", "text": "ossia.parameter status/release_count @type int @default 0 @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [970.0, 495.0, 440.0, 22.0]}},
      {"box": {"id": "obj-release-reason", "maxclass": "newobj", "text": "ossia.parameter status/last_release_reason @type string @default none @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [20.0, 535.0, 510.0, 22.0]}},
      {"box": {"id": "obj-frame", "maxclass": "newobj", "text": "ossia.parameter status/last_frame_json @type string @default empty @access get", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [560.0, 535.0, 490.0, 22.0]}},

      {"box": {"id": "obj-comment", "maxclass": "comment", "text": "OSCQuery status server: OSC 9011 / WebSocket+HTTP 5679", "patching_rect": [260.0, 808.0, 390.0, 20.0]}}
    ],
    "lines": [
      {"patchline": {"source": ["obj-in", 0], "destination": ["obj-route", 0]}},
      {"patchline": {"source": ["obj-route", 0], "destination": ["obj-port", 0]}},
      {"patchline": {"source": ["obj-route", 1], "destination": ["obj-gain", 0]}},
      {"patchline": {"source": ["obj-route", 2], "destination": ["obj-mute", 0]}},
      {"patchline": {"source": ["obj-port", 0], "destination": ["obj-out-port", 0]}},
      {"patchline": {"source": ["obj-gain", 0], "destination": ["obj-out-gain", 0]}},
      {"patchline": {"source": ["obj-mute", 0], "destination": ["obj-out-mute", 0]}},
      {"patchline": {"source": ["obj-route", 3], "destination": ["obj-state", 0]}},
      {"patchline": {"source": ["obj-route", 4], "destination": ["obj-run-state", 0]}},
      {"patchline": {"source": ["obj-route", 5], "destination": ["obj-run-id", 0]}},
      {"patchline": {"source": ["obj-route", 6], "destination": ["obj-sequence", 0]}},
      {"patchline": {"source": ["obj-route", 7], "destination": ["obj-token", 0]}},
      {"patchline": {"source": ["obj-route", 8], "destination": ["obj-note-count", 0]}},
      {"patchline": {"source": ["obj-route", 9], "destination": ["obj-tonality", 0]}},
      {"patchline": {"source": ["obj-route", 10], "destination": ["obj-bpm", 0]}},
      {"patchline": {"source": ["obj-route", 11], "destination": ["obj-mode", 0]}},
      {"patchline": {"source": ["obj-route", 12], "destination": ["obj-loop", 0]}},
      {"patchline": {"source": ["obj-route", 13], "destination": ["obj-tonality-enabled", 0]}},
      {"patchline": {"source": ["obj-route", 14], "destination": ["obj-prompt", 0]}},
      {"patchline": {"source": ["obj-route", 15], "destination": ["obj-pitch", 0]}},
      {"patchline": {"source": ["obj-route", 16], "destination": ["obj-frequency", 0]}},
      {"patchline": {"source": ["obj-route", 17], "destination": ["obj-activation", 0]}},
      {"patchline": {"source": ["obj-route", 18], "destination": ["obj-feature", 0]}},
      {"patchline": {"source": ["obj-route", 19], "destination": ["obj-cluster", 0]}},
      {"patchline": {"source": ["obj-route", 20], "destination": ["obj-instrument", 0]}},
      {"patchline": {"source": ["obj-route", 21], "destination": ["obj-error", 0]}},
      {"patchline": {"source": ["obj-route", 22], "destination": ["obj-unknown", 0]}},
      {"patchline": {"source": ["obj-route", 23], "destination": ["obj-release-count", 0]}},
      {"patchline": {"source": ["obj-route", 24], "destination": ["obj-release-reason", 0]}},
      {"patchline": {"source": ["obj-route", 25], "destination": ["obj-frame", 0]}},
      {"patchline": {"source": ["obj-expose", 0], "destination": ["obj-device", 0]}}
    ]
  }
}
